apiVersion: dscinitialization.opendatahub.io/v2
kind: DSCInitialization
metadata:
  name: <dsci_name>
  labels:
      app.kubernetes.io/name: dscinitialization
spec:
    applicationsNamespace: <application_namespace>
    monitoring:
        managementState: Managed
        namespace: <monitoring_namespace>
    trustedCABundle:
        customCABundle: ''
        managementState: Managed
