apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  name: <dsci_name>
  labels:
      app.kubernetes.io/created-by: <operator_yaml_label>
      app.kubernetes.io/instance: <dsci_name>
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: dscinitialization
      app.kubernetes.io/part-of: <operator_yaml_label>
spec:
    applicationsNamespace: <application_namespace>
    monitoring:
        metrics:
            replicas: 2
            resources:
                cpulimit: 500m
                cpurequest: 100m
                memorylimit: 512Mi
                memoryrequest: 256Mi
            storage:
                retention: 1d
                size: 5Gi
        traces:
            sampleRatio: "0.1"
            storage:
                backend: "pv"
                size: "5Gi"
        managementState: <monitoring_value>
        namespace: <monitoring_namespace>
    serviceMesh:
        auth:
            audiences:
                - 'https://kubernetes.default.svc'
        controlPlane:
            metricsCollection: Istio
            name: data-science-smcp
            namespace: istio-system
        managementState: Managed
    trustedCABundle:
        customCABundle: ''
        managementState: Managed
