- op: add
  path: /spec/template/spec/providerSpec/value/gpus
  value:
   - count: 2
     type: nvidia-tesla-v100
- op: add
  path: /spec/template/spec/providerSpec/value/onHostMaintenance
  value: Terminate
- op: replace
  path: /spec/template/spec/providerSpec/value/machineType
  value: n1-standard-4
- op: replace
  path: /spec/replicas
  value: 