kind: List
metadata: {}
apiVersion: v1
items:
  -   apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
          name: redhat-ods-operator
  -   apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
          name: rhods-operator
          namespace: redhat-ods-operator
      spec:
          channel: stable
          installPlanApproval: Automatic
          name: rhods-operator
          source: redhat-operators
          sourceNamespace: openshift-marketplace
  -   apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
          name: redhat-operators
          namespace: redhat-ods-operator
