- op: replace
  path: /spec/template/spec/providerSpec/value/machineType
  value: n1-standard-4
- op: add
  path: /spec/template/spec/providerSpec/value/onHostMaintenance
  value: Terminate
- op: replace
  path: /spec/replicas
  value: 2