apiVersion: v1
kind: Namespace
metadata:
  name: kube-amd-gpu

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kube-amd-gpu-operator-group
  namespace: kube-amd-gpu
spec: {}

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amd-gpu-operator
  namespace: kube-amd-gpu
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: amd-gpu-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace

