apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kmm

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-kmm-operator-group
  namespace: openshift-kmm
spec: {}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kernel-module-management
  namespace: openshift-kmm
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kernel-module-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
