apiVersion: v1
kind: ConfigMap
metadata:
    name: kernel-module-params
    namespace: nvidia-gpu-operator
data:
    nvidia.conf: |-
        NVreg_RegistryDwords="PeerMappingOverride=1;"
        NVreg_EnableStreamMemOPs=1
---
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
    name: gpu-cluster-policy
spec:
    daemonsets:
        rollingUpdate:
            maxUnavailable: "1"
        updateStrategy: RollingUpdate
    dcgm:
        enabled: true
    dcgmExporter:
        config:
            name: console-plugin-nvidia-gpu
        enabled: true
        serviceMonitor:
            enabled: true
    devicePlugin:
        config:
            default: ""
            name: ""
        enabled: true
        mps:
            root: /run/nvidia/mps
    driver:
        certConfig:
            name: ""
        enabled: true
        kernelModuleConfig:
            name: kernel-module-params
        kernelModuleType: auto
        licensingConfig:
            configMapName: ""
            nlsEnabled: false
        rdma:
            enabled: true
            useHostMofed: false
        repoConfig:
            configMapName: ""
        useNvidiaDriverCRD: false
        upgradePolicy:
            autoUpgrade: true
            drain:
                deleteEmptyDir: false
                enable: false
                force: false
                timeoutSeconds: 300
            maxParallelUpgrades: 1
            maxUnavailable: 25%
            podDeletion:
                deleteEmptyDir: false
                force: false
                timeoutSeconds: 300
            waitForCompletion:
                timeoutSeconds: 0
        virtualTopology:
            config: ""
    gdrcopy:
        enabled: true
    gds:
        enabled: false
    gfd:
        enabled: true
    mig:
        strategy: single
    migManager:
        enabled: true
    nodeStatusExporter:
        enabled: true
    operator:
        defaultRuntime: crio
        initContainer: { }
        runtimeClass: nvidia
        use_ocp_driver_toolkit: true
    sandboxDevicePlugin:
        enabled: true
    sandboxWorkloads:
        defaultWorkload: container
        enabled: false
    toolkit:
        enabled: true
        installDir: /usr/local/nvidia
    validator:
        driver:
            env:
                -   name: DISABLE_DEV_CHAR_SYMLINK_CREATION
                    value: "true"
        plugin:
            env:
                -   name: WITH_WORKLOAD
                    value: "true"
    vfioManager:
        enabled: true
    vgpuDeviceManager:
        enabled: true
    vgpuManager:
        enabled: false
