apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhods-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rhods-test-runner
  namespace: redhat-rhods-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhods-test-runner
  namespace: redhat-rhods-operator
