*** Settings ***
Resource        ../ODHDashboard/ODHDashboard.robot
Resource        ../../Components/Menu.robot
Resource        ../../HybridCloudConsole/HCCLogin.robot
Resource        ../../HybridCloudConsole/Rhosak.robot
Resource        ../JupyterHub/LoginJupyterHub.robot
Resource        ../JupyterHub/JupyterHubSpawner.robot
Resource        ../JupyterHub/JupyterLabSidebar.robot
Resource        Rhosak.robot