apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: add-gpu
resources:
  - ../../base/
patches:
  - path: gpu.yaml
    target:
      kind: MachineSet
  - path: gpu-remove-zone.yaml
    target:
      kind: MachineSet
      name: ".*[^(westus)]"  # regions without availability zones. If needed, add | <region name> after westus
