*** Settings ***
Resource  InstalledOperators/InstalledOperators.robot
Resource  InstalledOperators/UninstallODH.robot
Resource  OCPMenu.robot
Resource  OperatorHub/InstallODH.robot
Resource  OperatorHub/OperatorHub.robot
Resource  Page.robot
Resource  Monitoring/Metrics.robot
Resource  Pods/Pods.robot
Resource  Builds/Builds.robot
Resource  ImageStream/ImageStream.robot
Resource  ConfigMaps/ConfigMaps.robot
Resource  Secrets/Secrets.robot
