apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-get-latest-ocp-version
  labels:
    appstudio.openshift.io/application: <your-application-name>
    appstudio.openshift.io/component: <your-component-name>
  annotations:
    pipelines.appstudio.openshift.io/type: test
    test.appstudio.openshift.io/scenario: "Get latest OpenShift version"
spec:
  params:
    - name: prefix
      value: "4.17."
    - name: releaseStream
      value: "4-stable-multi"
    - name: host
      value: "multi.ocp.releases.ci.openshift.org"

  pipelineSpec:
    params:
      - name: prefix
        type: string
      - name: releaseStream
        type: string
      - name: host
        type: string

    tasks:
      - name: get-latest-ocp-version
        params:
          - name: prefix
            value: $(params.prefix)
          - name: releaseStream
            value: $(params.releaseStream)
          - name: host
            value: $(params.host)
        taskSpec:
          params:
            - name: prefix
              type: string
            - name: releaseStream
              type: string
            - name: host
              type: string
          steps:
            - name: get-latest-from-ci
              ref:
                name: eaas-get-latest-openshift-version-by-prefix
              params:
                - name: prefix
                  value: $(params.prefix)
                - name: releaseStream
                  value: $(params.releaseStream)
                - name: host
                  value: $(params.host)

            - name: print-version
              image: registry.access.redhat.com/ubi9/ubi-minimal
              script: |
                #!/usr/bin/env bash
                set -euo pipefail

                echo "Latest OCP version for prefix $(params.prefix) / stream $(params.releaseStream):"

                # 'steps.get-latest-from-ci.results.version' expands to the result file path
                echo -n "Version: "
                cat "$(steps.get-latest-from-ci.results.version)"

