apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: rhoai-cluster-provision-test
  namespace: rhoai-tenant
  labels:
    appstudio.openshift.io/application: testops-playpen
    appstudio.openshift.io/component: rhoai-health
    test.appstudio.openshift.io/type: integration
  annotations:
    test.appstudio.openshift.io/kind: cluster-provision
    test.appstudio.openshift.io/description: "Provision Hypershift cluster on AWS and run RHOAI integration tests"
spec:
  application: testops-playpen
  contexts:
    - name: application
      description: RHOAI integration testing with cluster provisioning
  params:
    # Cluster provisioning parameters
    - name: CLUSTER_NAME
      value: "rhoai-test-$(date +%s)"
    - name: HYPERSHIFT_AWS_REGION
      value: "us-east-1"
    - name: HYPERSHIFT_NODE_COUNT
      value: "3"
    - name: HYPERSHIFT_INSTANCE_TYPE
      value: "m5.xlarge"
    - name: OPENSHIFT_VERSION
      value: "4.17"
    
    # Test execution parameters
    - name: SNAPSHOT
      value: "{{SNAPSHOT}}"
    - name: TEST_IMAGE
      value: "{{SNAPSHOT_IMAGE}}"
  
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/konflux-ci/build-definitions
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/integration-test-with-hypershift.yaml
  
  environment:
    name: staging
    type: POC
