name: Lint
on: [push, pull_request]

jobs:
  run_lint:
    name: black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.2

      - name: Install black formater
        run: pip install black

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            if [[ $file == *.py ]]; then
               black $file --check --diff
            fi
          done
