name: dryrun_robot

# Controls when the workflow will run
on: [push, pull_request]
  # Triggers the workflow on push or pull request events but only for the "master" branch

permissions:
    contents: write
    pull-requests: write
    issues: read
    packages: none
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dryrun:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 #   permissions:
 #       contents: write
  #      pull-requests: write
 #       issues: read
 #       packages: none
 #   permissions: write-all
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Execute ods-ci dryrun
        run: |
          mv test-variables.yml.example test-variables.yml
          ./run_robot_test.sh --extra-robot-args '--dryrun' --skip-oclogin true --no-output-subfolder true

      # Runs a set of commands using the runners shell
      - name: Parse output
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          report_path: test-output
          gh_access_token: ${{ secrets.github_token }}
          show_passed_tests: false
